apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  master.cnf: |
    [mysqld]
    server-id       = 2
    pid-file        = /var/run/mysqld/mysqld.pid
    socket          = /var/run/mysqld/mysqld.sock
    datadir         = /var/lib/mysql