kind: Pod
apiVersion: v1
metadata:
  name: module-builder
spec:
  containers:
    - name: module-builder
      image: quay.io/sferr/ansible-module-builder:latest
      command: ["tail", "-f", "/dev/null"]
      volumeMounts:
        - name: my-environment1
          mountPath: /var/lib/awx/venv/my-environment1
  volumes:
    - name: my-environment1
      persistentVolumeClaim:
        claimName: my-environment1
