apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: build2
  name: build2
  namespace: build-demo
spec:
  failedBuildsHistoryLimit: 5
  output:
    to:
      kind: ImageStreamTag
      name: build2:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    type: Docker
  successfulBuildsHistoryLimit: 5
